[tool.poetry]
name = "picongpuanalysis"
version = "0.1.0"
description = "A library for analyzing PIConGPU simulations"
authors = ["Finn-Ole Carstens <f.carstens@hzdr.de>"]

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.20"
scipy = "^1.6"
openpmd_api = "^0.15.2"
matplotlib = "^3.9"
